### ISSUE TITLE
About the performance on the FaceShifter Dataset

### ISSUE THREAD

**Issue by Zoky-2020** [YZY-stack/StA4Deepfake#4]
Hi, thank you for your great work and for releasing the code.

I attempted to validate the performance of StA on the Celeb-DF-v2 and FaceShifter datasets using the provided checkpoint. The video-level AUCs I obtained were 0.9333 for Celeb-DF-v2 and 0.8713 for FaceShifter.

The reproduced performance on Celeb-DF-v2 aligns closely with the results reported in the paper and significantly outperforms previous deepfake video detection methods. However, the performance on FaceShifter falls considerably behind previous methods. Could you provide some insight into why this performance gap exists?

**Comment by YZY-stack** [comment]
Hi! Thank you for your interest in our work.

I haven't reported the results of FaceShifter because I find this evaluation set can be very "tricky". I developed DeepfakeBench and have implemented more than 30 detection methods. However, I haven't seen any detection method achieve an AUC result higher than 90 on the dataset we used (DeepfakeBench released dataset version). Even some well-known state-of-the-art methods like SBI only achieve 75% AUC on FaceShifter. I don't know why some methods can achieve such high results on FaceShifter. I'm even not sure if they used the c23 version or the raw version.

I have some empirical experience in tuning models on FaceShifter. I don't know if it's useful for you.

1. It seems that FaceShifter (Fsh) can be spatially challenging (difficult for image detectors), and CDF-v2 is temporally challenging (difficult for video detectors). Video methods can achieve higher results on Fsh but fail to achieve higher results on CDF-v2. For example, AltFreezing achieves 99% on Fsh but only 89% on CDF. In contrast, SBI achieves 93% on CDF-v2 but only 75% on Fsh.

2. Stronger data augmentations help improve results on CDF but hurt results on Fsh.

We will continue to explore the underlying reasons. At present, we are not sure if the Fsh dataset used in each paper is perfectly aligned. That's why I built DeepfakeBench and use the aligned dataset for training and testing.

Thanks for your comment.

**Comment by Zoky-2020** [comment]
Thank you very much for your response and for sharing your experience—it has been incredibly helpful to me.

I, too, have experimented with various experimental settings, including but not limited to data preprocessing methods, model architectures, and optimization algorithms. Just as you mentioned, none of these approaches achieved the 0.99+ video-level AUC reported in previous papers on the FaceShifter/c23/videos dataset.

Once again, thank you for your insights.
